disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - nesting
  - function_parameter_count
  - empty_count
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
opt_in_rules: # some rules are only opt-in
  - control_statement
  - trailing_newline
  - colon
  - comma
  - multiline_arguments
  - multiline_parameters
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
cyclomatic_complexity:
  warning: 40
  error: 40
  ignores_case_statements: true
#- private_outlet # IBOutlets should be private to avoid leaking UIKit to higher layers.
included: # paths to include during linting. `--path` is ignored if present.

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Carthage
  - Project/R.generated.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly. Give warning only for force casting

force_try:
  severity: warning # explicitly. Give warning only for force try

type_body_length:
  - 300 # warning
  - 500 # error

line_length:
  - 300

# or they can set both explicitly
file_length:
  warning: 1500
  error: 2000

large_tuple: # warn user when using 5 values in tuple, give error if there are 6
  - 5
  - 6

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 55
  excluded: iPhone # excluded via string
reporter: "xcode"

